export const data = [
    {
        photo: "/projects/first.png",
        name: "Galleria Slideshow Site",
        languages: "TypeScript, TailWind CSS",
        live: "https://galleryslideshowpage.vercel.app/",
        git: "https://github.com/DatoAbuta/galleryslideshowpage",
    },
    {
        photo: "/projects/second.png",
        name: "Sign Up Form",
        languages: "Typescript",
        live: "https://intro-component-sign-up-form-beta.vercel.app/",
        git: "https://github.com/DatoAbuta/Intro-Component-Sign-Up-Form",
    },
    {
        photo: "/projects/third.png",
        name: "Ask Girl For Date",
        languages: "Typescript",
        live: "https://askgirlfordate.vercel.app/",
        git: "https://github.com/DatoAbuta/askgirlfordate",
    },
    {
        photo: "/projects/fourth.png",
        name: "Entertainment Site",
        languages: "Typescript",
        live: "https://entertainment-web-xi.vercel.app/",
        git: "https://github.com/DatoAbuta/EntertainmentWeb",
    },
    {
        photo: "/projects/fifth.png",
        name: "Countries Site",
        languages: "Typescript",
        live: "https://countries-five-plum.vercel.app/",
        git: "https://github.com/DatoAbuta/countries",
    },
    {
        photo: "/projects/sixth.png",
        name: "Cards",
        languages: "React",
        live: "https://cards-david69699.vercel.app/",
        git: "https://github.com/DatoAbuta/cards",
    },
    {
        photo: "/projects/seventh.png",
        name: "Interactive Rating Component",
        languages: "React",
        live: "https://react4-lemon.vercel.app/",
        git: "https://github.com/DatoAbuta/react4",
    },
    {
        photo: "/projects/eigth.png",
        name: "QR Code Component",
        languages: "React",
        live: "https://reactfirst-gamma.vercel.app/",
        git: "https://github.com/DatoAbuta/reactfirst",
    },
    {
        photo: "/projects/nineth.png",
        name: "Dictionary Web App",
        languages: "HTML, CSS, JavaScript",
        live: "https://davaleba22-gamma.vercel.app/",
        git: "https://github.com/DatoAbuta/DictionaryWebPage",
    },
    {
        photo: "/projects/tenth.png",
        name: "TODO App",
        languages: "HTML, CSS, JavaScript",
        live: "https://todos-two-plum.vercel.app/",
        git: "https://todos-two-plum.vercel.app/",
    },
    {
        photo: "/projects/eleventh.png",
        name: "Random Advice Generator",
        languages: "HTML, CSS, JavaScript",
        live: "https://random-advice-ten.vercel.app/",
        git: "https://github.com/DatoAbuta/RandomAdvice",
    },
    {
        photo: "/projects/twelveth.png",
        name: "Tip Calculator App",
        languages: "HTML, CSS, JavaScript",
        live: "https://shualedurskoi3.vercel.app/",
        git: "https://github.com/DatoAbuta/shualedurskoi3",
    },
    {
        photo: "/projects/thirteenth.png",
        name: "Pod Request Access Page",
        languages: "HTML, CSS, JavaScript",
        live: "https://davaleba15-gold.vercel.app/",
        git: "https://github.com/DatoAbuta/Davaleba15",
    },
    {
        photo: "/projects/fourteenth.png",
        name: "Resolution Counter",
        languages: "HTML, CSS, JavaScript",
        live: "https://screen-resolution-counter.vercel.app/",
        git: "https://github.com/DatoAbuta/ScreenResolutionCounter",
    },
    {
        photo: "/projects/fifteenth.png",
        name: "Weather App",
        languages: "HTML, CSS, JavaScript",
        live: "https://amindebi.vercel.app/",
        git: "https://github.com/DatoAbuta/amindebi",
    },
]